version: "3.9"

services:

  db: #Hostname
    container_name: little_library_db
    image: mysql:8.2
    volumes:
      - ${DB_NAME}:/var/lib/mysql
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped

  server: #Hostname
    container_name: little_library
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ./server/src:/app
    environment:
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_HOSTNAME: ${DB_HOSTNAME}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  dev_db: